const SET_USER = 'SET_USER'
const SET_FACEBOOK = 'SET_FACEBOOK'
const SET_INSTAGRAM = 'SET_INSTAGRAM'
const SET_ONLYFANS = 'SET_ONLYFANS'
const SET_TIKTOK = 'SET_TIKTOK'

export default {
  SET_USER,
  SET_FACEBOOK,
  SET_INSTAGRAM,
  SET_ONLYFANS,
  SET_TIKTOK,
}
