const SET_NAME = 'SET_NAME'
const SET_ADDRESS = 'SET_ADDRESS'
const SET_AMOUNT_AVAILABLE = 'SET_AMOUNT_AVAILABLE'
const SET_ARCHIVEMENTS_AVAILABLE = 'SET_ARCHIVEMENTS_AVAILABLE'
const SET_CARDS = 'SET_CARDS'
const SET_LASTNAME = 'SET_LASTNAME'
const SET_LOGO = 'SET_LOGO'
const SET_EMAIL = 'SET_EMAIL'

export default {
  SET_NAME,
  SET_ADDRESS,
  SET_AMOUNT_AVAILABLE,
  SET_ARCHIVEMENTS_AVAILABLE,
  SET_CARDS,
  SET_LASTNAME,
  SET_LOGO,
  SET_EMAIL,
}
