const SWITCH_SHOW = 'SWITCH_SHOW'
const SET_TITLE = 'SET_TITLE'
const SET_TITLE_HELP = 'SET_TITLE_HELP'
const SET_MESSAGE = 'SET_MESSAGE'
const SET_TYPE = 'SET_TYPE'
const SET_CLOSABLE = 'SET_CLOSABLE'

export default {
  SWITCH_SHOW,
  SET_TITLE,
  SET_TITLE_HELP,
  SET_MESSAGE,
  SET_TYPE,
  SET_CLOSABLE,
}
